config/routes.rb
# -*- encoding : utf-8 -*-

Rpmp::Application.routes.draw do

  namespace :sys do
    root :to => 'admin#facet', as: 'admin_root'
    resources :users do
      collection do
        get 'all', 'disabled'
      end
    end
    resources :departments, :roles, :mods do
      post 'tune_order', :on => :collection
    end
    resources :configs
    resources :dumps, :only => [:index,:create,:destroy] do
      post 'download', :on => :member
    end
    resources :projects do
      get *%w(all inactive), :on => :collection
      resources :role_members, :member_roles do
        get 'edit', :action => 'edit_all', :on => :collection
      end
    end
    resources :announcements do
      post 'issue', :on => :member
    end
    resource :logs, :only => :show
    controller :console, path: 'console', as: 'console' do
      get '/' => :index
      post 'run'
    end
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end

  controller :personal, path: 'personal', module: 'sys', as: 'personal' do
    get '/' => :index
    get 'edit'
    put 'update'
  end

  resources :projects do
    member do
      get *%w(role_members member_roles members)
    end
    collection do
      get *%w(all inactive activities weeklies issues_statistic
            issues issues_unsolved issues_to_test issues_closed issues_unclosed
            tasks tasks_todo my_tasks my_tasks_todo task_ranks task_matrix)
    end
    resources :attachments do
      member do
        get 'download', 'image'
      end
    end
    resources :modus do
      member do
        get *%w(requirements issues tasks)
      end
    end
    resources :tags, :only => [:index, :show] do
      member do
        get *%w(documents requirements issues tasks)
      end
    end
    resources :comments, :activities, :releases
    resources :documents, :meetings, :customers, :communications, :weeklies do
      get 'history', :on => :member
    end
    resources :requirements do
      get 'uncompleted', :on => :collection
      get 'history', :on => :member
    end
    resources :goals, :milestones, :controller => 'goals' do
      member do
        get 'release', 'history'
      end
    end
    resources :tests do
      get 'history', :on => :member
      resources :issues, :controller => :test_issues do
        collection do
          get 'unsolved', 'to_test'
        end
        get 'history', :on => :member
      end
    end
    resources :issues do
      collection do
        get *%w(unsolved to_test closed unclosed associated statistic)
      end
      member do
        get *%w(associated history solve regress reopen)
      end
    end
    resources :tasks, :my_tasks do
      collection do
        get *%w(todo requirements issues)
      end
      member do
        get *%w(history requirements issues)
        post *%w(receive rank)
      end
    end
    resource :task_statistics, only: 'show' do
      get 'ranks','matrix'
    end

    resources :revisions do
      get 'entries', :on => :member
      collection do
        get 'statistic'
        get 'diff/:entry_id(/:diff_with)', action: 'diff'
        get 'source/:entry_id', :action => 'source'
      end
    end
    post ':controller/:id/pm_confirm', :action => :pm_confirm
  end

  resources :announcements, :only => [:index, :show] do
    get 'current', :on => :collection
  end
  resources :departments, :only => [:index] do
    get 'users', :on => :member
  end
  resources :messages, :except => :update do
    collection do
      get 'received', 'sent'
    end
    get 'reply', :on => :member
  end

  match 'announcement' => 'announcements#current', :as => 'current_announcement'
  root :to => 'projects#index'

end

app/models/meeting.rb
# -*- encoding : utf-8 -*-

class Meeting < ActiveRecord::Base
  include ModelSupport
  include ProjectResource

  belongs_to_user :emcee
  has_attachments
  setup_associations [[:participants, :user]]
end

app/controllers/meetings_controller.rb
# -*- encoding : utf-8 -*-

class MeetingsController < ProjectResourceController

  def create
    super { set_associations 'participant', 'user' }
  end

  def update
    super { set_associations 'participant', 'user' }
  end
end

app/views/meetings/_form.html.haml
= form_for @meeting, :url => @meeting.new_record? ? collection_path : resource_path(@meeting), :html => {:multipart => true} do |f|
  = render 'application/error_messages', :model => @meeting
  %table
    %tr
      %td 日期
      %td= render 'application/date-popup', :field => 'holding_on', :f => f
    %tr
      %td 主持人
      %td= f.collection_select :emcee_id, @project.users, :id, :name
    %tr
      %td 参会人员
      %td
        .user_candidates
          - ids=@meeting.participant_ids
          - @project.users.each do |user|
            %div
              = check_box_tag 'participant_ids[]', user.id, ids.include?(user.id), :id => "participant_#{user.id}"
              = label_tag "participant_#{user.id}", user.name
    %tr
      %td 会议主题
      %td= f.text_field :abstract
    %tr
      %td 会议内容
      %td= f.text_area :content, :rows => 5
    %tr
      %td 备注
      %td= f.text_area :memo, :rows => 2
    %tr
      %td 附件
      %td
        - unless @meeting.new_record?
          = render 'attachments/attachments', :can_delete => true
        = render 'attachments/new_attachments'
    - unless @meeting.new_record?
      %tr
        %td 已确认
        %td{:id=>'confirmed'}
          = @meeting.confirmed ? '是' : '否'
          - if not @meeting.confirmed and @cu.pm?(@project)
            = link_to '主管确认', project_meeting_path(@project,@meeting)+'/pm_confirm', :method => :post, :remote => true
    %tr
      %td 标签
      %td= text_field_tag :tags, (resource.tags.map &:name).join(' '), :size => 30
  .actions
    = f.submit '保存'

app/views/meetings/edit.html.haml
%h3 会议纪要

= render 'form'

= link_to '详细', resource_path(@meeting), remote_options
\|
= link_to '返回', collection_path, remote_options

app/views/meetings/index.html.haml
%h3 会议纪要

%table.list-table
  %tr
    %th 日期
    %th 主持人
    %th 会议主题
    %th 评论
    %th 记录人
    %th 记录时间
    %th

  - dl=7.days.ago
  - @meetings.each do |m|
    %tr{:id => "r_#{m.id}"}
      %td= m.holding_on
      %td= m.emcee.name
      %td= m.abstract
      %td= non_zero(m.comments_count)
      %td= m.registrar.name
      %td= m.created_at.datetime_ydyn
      %td
        = link_to '详细', resource_path(m), remote_options
        - if m.created_at > dl and (not m.confirmed or @cu.pm?(@project))
          = link_to '修改', edit_resource_path(m), remote_options
          = link_to '删除', resource_path(m), :confirm => '确定要删除吗?', :method => :delete, :remote => true
= will_paginate @mettings
%br

= link_to '增加', new_resource_path, remote_options

app/views/meetings/new.html.haml
%h3 会议纪要

= render 'form'

= link_to '返回', collection_path, remote_options

app/views/meetings/show.html.haml
%h3 会议纪要

%table.columns
  %tr
    %td 日期:
    %td= @meeting.holding_on
  %tr
    %td 主持人:
    %td= @meeting.emcee.name
  %tr
    %td 参会人员:
    %td
      - @meeting.participants.each do |user|
        = user.name
  %tr
    %td 会议主题:
    %td= @meeting.abstract
  %tr
    %td 会议内容:
    %td
      %pre= @meeting.content
  %tr
    %td 记录人:
    %td= @meeting.registrar.name
  %tr
    %td 备注:
    %td= @meeting.memo
  %tr
    %td 记录时间:
    %td= resource.created_at.datetime_ydyn
  %tr
    %td 上次修改:
    %td= resource.updated_at.datetime_ydyn unless resource.updated_at==resource.created_at
  %tr
    %td 附件
    %td= render 'attachments/attachments'

%br
= render 'tags/tags'

%br
= render 'comments/comments'

%br
= link_to history_project_meeting_path(@project,@meeting), resource_history_link_options do
  .title 历史...
#resource_history

%br
- if not @meeting.confirmed or @cu.pm?(@project)
  = link_to '修改', edit_resource_path(@meeting), remote_options
  \|
= link_to_function '评论', 'new_comment()'
\|
= link_to '返回', collection_path, remote_options