config/routes.rb
# -*- encoding : utf-8 -*-

Rpmp::Application.routes.draw do

  namespace :sys do
    root :to => 'admin#facet', as: 'admin_root'
    resources :users do
      collection do
        get 'all', 'disabled'
      end
    end
    resources :departments, :roles, :mods do
      post 'tune_order', :on => :collection
    end
    resources :configs
    resources :dumps, :only => [:index,:create,:destroy] do
      post 'download', :on => :member
    end
    resources :projects do
      get *%w(all inactive), :on => :collection
      resources :role_members, :member_roles do
        get 'edit', :action => 'edit_all', :on => :collection
      end
    end
    resources :announcements do
      post 'issue', :on => :member
    end
    resource :logs, :only => :show
    controller :console, path: 'console', as: 'console' do
      get '/' => :index
      post 'run'
    end
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end

  controller :personal, path: 'personal', module: 'sys', as: 'personal' do
    get '/' => :index
    get 'edit'
    put 'update'
  end

  resources :projects do
    member do
      get *%w(role_members member_roles members)
    end
    collection do
      get *%w(all inactive activities weeklies issues_statistic
            issues issues_unsolved issues_to_test issues_closed issues_unclosed
            tasks tasks_todo my_tasks my_tasks_todo task_ranks task_matrix)
    end
    resources :attachments do
      member do
        get 'download', 'image'
      end
    end
    resources :modus do
      member do
        get *%w(requirements issues tasks)
      end
    end
    resources :tags, :only => [:index, :show] do
      member do
        get *%w(documents requirements issues tasks)
      end
    end
    resources :comments, :activities, :releases
    resources :documents, :meetings, :customers, :communications, :weeklies do
      get 'history', :on => :member
    end
    resources :requirements do
      get 'uncompleted', :on => :collection
      get 'history', :on => :member
    end
    resources :goals, :milestones, :controller => 'goals' do
      member do
        get 'release', 'history'
      end
    end
    resources :tests do
      get 'history', :on => :member
      resources :issues, :controller => :test_issues do
        collection do
          get 'unsolved', 'to_test'
        end
        get 'history', :on => :member
      end
    end
    resources :issues do
      collection do
        get *%w(unsolved to_test closed unclosed associated statistic)
      end
      member do
        get *%w(associated history solve regress reopen)
      end
    end
    resources :tasks, :my_tasks do
      collection do
        get *%w(todo requirements issues)
      end
      member do
        get *%w(history requirements issues)
        post *%w(receive rank)
      end
    end
    resource :task_statistics, only: 'show' do
      get 'ranks','matrix'
    end

    resources :revisions do
      get 'entries', :on => :member
      collection do
        get 'statistic'
        get 'diff/:entry_id(/:diff_with)', action: 'diff'
        get 'source/:entry_id', :action => 'source'
      end
    end
    post ':controller/:id/pm_confirm', :action => :pm_confirm
  end

  resources :announcements, :only => [:index, :show] do
    get 'current', :on => :collection
  end
  resources :departments, :only => [:index] do
    get 'users', :on => :member
  end
  resources :messages, :except => :update do
    collection do
      get 'received', 'sent'
    end
    get 'reply', :on => :member
  end

  match 'announcement' => 'announcements#current', :as => 'current_announcement'
  root :to => 'projects#index'

end

app/models/revision.rb
# -*- encoding : utf-8 -*-

class Revision < ActiveRecord::Base
  include ModelSupport

  belongs_to_project
  has_many :revision_entries, :dependent => :destroy
  default_scope :order => 'id desc'

  ACTION_MAP={'A' => '创建', 'M' => '修改', 'D' => '删除'}

  def self.filter(params)
    sc=scoped
    return sc if params.blank?

    author,revision_no=params['author'],params['revision_no']
    sc=sc.where('author = ?', author) unless author.blank?
    unless revision_no.blank?
      revision_no=revision_no.sub(/^r/, '')
      sc=sc.where('revision_no = ?', revision_no) unless revision_no.blank?
    end

    cc,path=params['commit_comment'],params['path']
    sc=sc.where('commit_comment like ?', "%#{cc}%") unless cc.blank?
    unless path.blank?
      sc=sc.joins(:revision_entries).where('revision_entries.path' => path)
      path_action=params['path_action']
      sc=sc.where('revision_entries.action' => path_action) unless path_action.blank?
    end
    sc
  end

  def self.commit_statistic(params)
    date_from,date_to,project_id=date_range_and_project_id(params)

    Task.connection.select_all <<-SQL
      select
        author scm_name,
        su.name rpmp_name,
        count(*) commit_count,
        sum(revision_entries_count) entries_count,
        sum(revision_entries_count)/count(*) avg_entries
      from revisions
      left join sys_users su on author=su.scm_username
      where
        project_id = #{project_id}
        #{" and commit_at >= '#{date_from}'" unless date_from.blank?}
        #{" and commit_at <= '#{date_to}'" unless date_to.blank?}
      group by author
      order by commit_count desc
    SQL
  end

end

app/controllers/revisions_controller.rb
# -*- encoding : utf-8 -*-

class RevisionsController < ProjectResourceController
  actions :only => [:ranks, :entries]
  require 'time'
  require 'rexml/document'
  include REXML

  def index
    if !@cu.admin_or_root? && @cu.scm_username.blank?
      flash[:err_msg] = '没有权限'
      redirect_to projects_path
      return
    end

    check_and_update_revisions unless params[:page]

    @filter=params[:path].nil? ? {} : params
    session[:revision_filter_path]=params[:path]
    @filter['path_action']='' if @filter['path'].blank?
    @revisions=@project.revisions.filter(@filter).paginate(:page => params[:page])
  end

  def entries
    @filter_path=session[:revision_filter_path]
    @revision=Revision.find(params[:id])
    @entries=@revision.revision_entries
    render '_entries'
  end

  def source
    return unless set_revision_entry
    source_text=`svn cat -r #{@revision.revision_no} #{@project.scm_project_repos()}#{@revision_entry.path}`
    render :text => source_text
  end

  def diff
    return unless set_revision_entry
    diff_with, rno=params[:diff_with], @revision.revision_no
    diff_with=rno-1 if diff_with.blank?
    diff_text=`svn diff -r #{diff_with}:#{rno} #{@project.scm_project_repos()}#{@revision_entry.path}`
    render :text => diff_text
  end

  def statistic
    if params[:date_from].nil? && params[:date_to].nil?
      df=Date.current << 1
      params[:date_from]=df.strftime('%Y-%-m-%-d')
    end
     @member_commits=Revision.commit_statistic(params)
  end

  private

  def set_revision_entry
    @revision_entry=RevisionEntry.find(params[:entry_id]) rescue nil
    unless @revision_entry
      render :text => 'entry not found.'
      return false
    end
    @revision=Revision.find(@revision_entry.revision_id) rescue nil
    unless @revision and @revision.project_id==@project.id
      render :text => 'revision not found.'
      return false
    end
    true
  end

  def check_and_update_revisions
    last_revision=@project.revisions.order('revision_no desc').first
    if last_revision.nil? or last_revision.created_at < 1.minutes.ago
      new_last_revision=fetch_last_revision
      if new_last_revision
        last_rno=last_revision ? last_revision.revision_no : -1
        if last_rno < new_last_revision.revision_no
          update_revisions last_rno+1
        end
      end
    end
  rescue Exception => e
    puts e
  end

  def code_base
    @project.scm_project_base()
  end

  def fetch_last_revision
    svn_log=`svn --xml -l 1 log #{code_base}`
    xml=Document.new(svn_log)
    revisions=parse_revisions(xml)
    revisions[0] if revisions.length>0
  end

  def update_revisions(from_revision)
    svn_log=`svn --xml -v -r #{from_revision}:HEAD log #{code_base}`
    xml=Document.new(svn_log)
    revisions=parse_revisions(xml)
    revisions.each do |revision|
      revision.save
    end
  end

  def parse_revisions(xml)
    revisions=[]
    xml.root.each_element do |entry|
      revision=Revision.new
      revision.project=@project
      revision.revision_no=entry.attribute('revision').value.to_i
      revision.author=entry.get_elements('author')[0].text
      revision.commit_at=Time.parse(entry.get_elements('date')[0].text).localtime()
      revision.commit_comment=entry.get_elements('msg')[0].text
      paths=entry.get_elements('paths')
      if paths.length > 0
        parse_entries(revision, paths[0])
        revision.revision_entries.sort_by! &:path
      end
      revisions << revision
    end
    revisions
  end

  def parse_entries(revision, paths_node)
    paths_node.each_element do |path|
      entry=RevisionEntry.new
      entry.project=@project
      entry.kind=path.attribute('kind').value
      entry.action=path.attribute('action').value
      entry.path=path.text
      revision.revision_entries << entry
    end
  end

end

app/views/revisions/_entries.html.haml
%ul.revision_entries
  - action_map=Revision::ACTION_MAP
  - @entries.each do |m|
    %li
      = action_map[m.action]||'修改'
      %span{:class=>(@filter_path and @filter_path==m.path)? 'found_entry':''}= m.path
      = link_to_function '查看1', "view_source('#{m.path}',#{m.revision.revision_no})", :class => 'view_source' unless m.action=='D'
      = link_to_function '查看2', "view_source2('#{m.path}',#{m.id})", :class => 'view_source' unless m.action=='D' or m.kind=='dir'
      = link_to_function '变更', "diff_revision('#{m.path}',#{m.id})", :class => 'view_source' if m.action=='M'

app/views/revisions/index.html.haml
%h3
  代码提交
  %span(style="font-size:12px;float:right;")
    = link_to '统计', statistic_project_revisions_path(@project), remote_options

#filterDiv
  = remote_filter_form_tag do |f|
    版本
    = text_field_tag 'revision_no', @filter['revision_no'], :style=>'width:40px;'
    提交人
    = text_field_tag 'author', @filter['author'], :style=>'width:70px;'
    评论
    = text_field_tag 'commit_comment', @filter['commit_comment'], :style=>'width:80px;'
    全路径
    = text_field_tag 'path', @filter['path'], :style=>'width:150px;'
    操作
    = select_tag 'path_action', options_for_select(Revision::ACTION_MAP.invert,@filter['path_action']), :include_blank => true
    .actions
      = submit_tag '筛选'

%ul#revisions
  - @revisions.each do |r|
    %li{:id => "r#{r.id}"}
      = r.commit_at.today? ? r.commit_at.strftime("%H:%M") : r.commit_at.strftime("%Y-%-m-%-d %H:%M")
      = "r#{r.revision_no}"
      = r.author
      = link_to "文件数：#{r.revision_entries_count}", entries_project_revision_path(@project,r), :remote => true, 'data-update' => "r#{r.id}_entries", 'data-toggle' => 'true'
      -if r.commit_comment
        %span.revision_comment= r.commit_comment
    %li{:id => "r#{r.id}_entries"}(style="display:none;")
= will_paginate @revisions

%br

#source_explorer(style="display:none;padding:.5em .1em;")
  %iframe(seamless)
#source_explorer2(style="display:none;padding:.5em .5em;")
  %pre
#diff_explorer(style="display:none;padding:.5em .5em;")
  %pre

:javascript
  $(function(){
    $('#source_explorer').dialog({width:700,height:500,position:{my:'left top',at:'left+120 top+50'},autoOpen:false})
    $('#source_explorer2').dialog({width:700,height:500,position:{my:'left top',at:'left+140 top+60'},autoOpen:false})
    $('#diff_explorer').dialog({width:600,height:450,position:{my:'left top',at:'left+170 top+70'},autoOpen:false})
  })

  function view_source(path,revision_no){
    $('#source_explorer iframe').attr('src',"#{@project.scm_project_repos(!request.remote_ip.start_with?('192.168.')) rescue ''}"+path+"?p="+revision_no)
    $('#source_explorer').dialog( "option", "title", 'source(direct): '+path ).dialog('open')
  }

  function view_source2(path,entry_id){
    $('#source_explorer2 pre').text('loading...')
    $('#source_explorer2').dialog( "option", "title", 'source(delegate): '+path ).dialog('open')
    $.get("#{project_revisions_path}/source/"+entry_id,function(text,status,xhr){
      $('#source_explorer2 pre').text(text)
    })
  }

  function diff_revision(path,entry_id,diff_with){
    $('#diff_explorer pre').text('loading...')
    $('#diff_explorer').dialog( "option", "title", 'diff: '+path ).dialog('open')
    var url="#{project_revisions_path}/diff/"+entry_id
    if(diff_with)url+="/"+diff_with
    $.get(url,function(text,status,xhr){
      $('#diff_explorer pre').text(text)
    })
  }

app/views/revisions/statistic.html.haml
%h3
  提交统计
  %span(style="font-size:12px;float:right;")
    = link_to '详细', project_revisions_path(@project), remote_options

#filterDiv
  = remote_filter_form_tag do |f|
    开始
    = render 'application/date-popup', :field => 'date_from', :v => params[:date_from],:can_empty=>true
    截止
    = render 'application/date-popup', :field => 'date_to', :v => params[:date_to],:can_empty=>true
    .actions
      = submit_tag '统计'

%table.list-table
  %tr
    %th 提交人
    %th RPMP 用户名
    %th 提交次数
    %th 平均文件数

  - @member_commits.each do |mc|
    %tr
      %td= mc['scm_name']
      %td= mc['rpmp_name']
      %td(class="number")= mc['commit_count']
      %td(class="number")= '%.2f' % mc['avg_entries'] if mc['avg_entries']
%br