config/routes.rb
# -*- encoding : utf-8 -*-

Rpmp::Application.routes.draw do

  namespace :sys do
    root :to => 'admin#facet', as: 'admin_root'
    resources :users do
      collection do
        get 'all', 'disabled'
      end
    end
    resources :departments, :roles, :mods do
      post 'tune_order', :on => :collection
    end
    resources :configs
    resources :dumps, :only => [:index,:create,:destroy] do
      post 'download', :on => :member
    end
    resources :projects do
      get *%w(all inactive), :on => :collection
      resources :role_members, :member_roles do
        get 'edit', :action => 'edit_all', :on => :collection
      end
    end
    resources :announcements do
      post 'issue', :on => :member
    end
    resource :logs, :only => :show
    controller :console, path: 'console', as: 'console' do
      get '/' => :index
      post 'run'
    end
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end

  controller :personal, path: 'personal', module: 'sys', as: 'personal' do
    get '/' => :index
    get 'edit'
    put 'update'
  end

  resources :projects do
    member do
      get *%w(role_members member_roles members)
    end
    collection do
      get *%w(all inactive activities weeklies issues_statistic
            issues issues_unsolved issues_to_test issues_closed issues_unclosed
            tasks tasks_todo my_tasks my_tasks_todo task_ranks task_matrix)
    end
    resources :attachments do
      member do
        get 'download', 'image'
      end
    end
    resources :modus do
      member do
        get *%w(requirements issues tasks)
      end
    end
    resources :tags, :only => [:index, :show] do
      member do
        get *%w(documents requirements issues tasks)
      end
    end
    resources :comments, :activities, :releases
    resources :documents, :meetings, :customers, :communications, :weeklies do
      get 'history', :on => :member
    end
    resources :requirements do
      get 'uncompleted', :on => :collection
      get 'history', :on => :member
    end
    resources :goals, :milestones, :controller => 'goals' do
      member do
        get 'release', 'history'
      end
    end
    resources :tests do
      get 'history', :on => :member
      resources :issues, :controller => :test_issues do
        collection do
          get 'unsolved', 'to_test'
        end
        get 'history', :on => :member
      end
    end
    resources :issues do
      collection do
        get *%w(unsolved to_test closed unclosed associated statistic)
      end
      member do
        get *%w(associated history solve regress reopen)
      end
    end
    resources :tasks, :my_tasks do
      collection do
        get *%w(todo requirements issues)
      end
      member do
        get *%w(history requirements issues)
        post *%w(receive rank)
      end
    end
    resource :task_statistics, only: 'show' do
      get 'ranks','matrix'
    end

    resources :revisions do
      get 'entries', :on => :member
      collection do
        get 'statistic'
        get 'diff/:entry_id(/:diff_with)', action: 'diff'
        get 'source/:entry_id', :action => 'source'
      end
    end
    post ':controller/:id/pm_confirm', :action => :pm_confirm
  end

  resources :announcements, :only => [:index, :show] do
    get 'current', :on => :collection
  end
  resources :departments, :only => [:index] do
    get 'users', :on => :member
  end
  resources :messages, :except => :update do
    collection do
      get 'received', 'sent'
    end
    get 'reply', :on => :member
  end

  match 'announcement' => 'announcements#current', :as => 'current_announcement'
  root :to => 'projects#index'

end

app/models/attachment.rb
# -*- encoding : utf-8 -*-

#require 'mini_magick'
class Attachment < ActiveRecord::Base
  include ModelSupport

  belongs_to_project
  belongs_to_user :presenter
  belongs_to :subject, :polymorphic => true, :counter_cache => true

  SELECT_FIELDS=column_names.delete_if { |e| e=='content' }.join(',')

  attr_accessor :luu_id

  after_create do
    save_activity :action => 'add_attachment',
                  :user_id => self.presenter_id,
                  :subject_type => self.subject_type,
                  :subject_id => self.subject_id
  end

  after_destroy do
    save_activity :action => 'del_attachment',
                  :subject_type => self.subject_type,
                  :subject_id => self.subject_id
  end

  def uploaded_attachment=(af)
    self.name = File.basename(af.original_filename)
    self.content_type = af.content_type.chomp
    self.content_size = af.size
    self.content = af.read
    if self.content_type=~/^image\//
      self.image=true
      self.image_width, self.image_height=0, 0
      #begin
      #  img=MiniMagick::Image.read(self.content)
      #  self.image_width,self.image_height=img["width"],img["height"]
      #rescue # Exception => e
      #end
    end
  end

end

app/controllers/attachments_controller.rb
# -*- encoding : utf-8 -*-

class AttachmentsController < ProjectResourceController
  actions :all, :except => [:show, :edit]

  def download
    send_attachment
  end

  def image
    send_attachment :disposition => 'inline' unless request.xhr?
  end

  protected

  def send_attachment(options={})
    @attachment=Attachment.find(params[:id])
    raise if @attachment.project_id != @project.id
    o = {:filename => @attachment.name, :type => @attachment.content_type, :disposition => 'attachment'}
    send_data(@attachment.content, o.update(options))
  end

end

app/views/attachments/_attachments.html.haml
#attachments.nestedResource
  %table.attachments
    - _att_host=if defined? att_host then att_host else resource end
    - unless _att_host.respond_to?(:attachments_count) and (_att_host.attachments_count.nil? or _att_host.attachments_count.zero?)
      - _att_host.attachments.each do |attachment|
        %tr{:id=>"r_#{attachment.id}"}
          %td= attachment.name
          %td= attachment.memo
          %td(style="text-align:right;")
            = (attachment.content_size+512) >> 10
            K
          %td= attachment.presenter.name if attachment.presenter
          %td= attachment.created_at.datetime_ydyn
          %td
            = link_to_function '查看', "view_image(#{attachment.id},'#{image_project_attachment_path(@project,attachment)}',#{attachment.image_width},600)" if attachment.image?
            = link_to '下载', download_project_attachment_path(@project,attachment)
            - if defined? can_delete and can_delete
              %td= link_to '删除', project_attachment_path(@project,attachment), :confirm => '确定要删除吗?', :method => :delete, :remote => true

app/views/attachments/_new_attachments.html.haml
#new_attachments.nestedResource
.title
  #atmh{:style => 'display:none'}
    .atm
      = file_field_tag 'attachments[][uploaded_attachment]'
      备注：
      = text_field_tag 'attachments[][memo]'
      - if defined? attachment_tag
        = hidden_field_tag 'attachments[][tag]',attachment_tag
      = link_to_function "取消", '$(this).parent().remove()'
  :javascript
    var atm_tmpl=$('#atmh').remove().html()
  = link_to_function '增加附件', '$("#new_attachments").append(atm_tmpl)'

app/views/attachments/index.html.haml
%h3 附件

%table.list-table
  %tr
    %th 所属资源
    %th 名称
    %th 类型
    %th 大小（KB）
    %th 提交人
    %th 提交时间
    %th 标签
    %th 备注
    %th

  - @attachments.each do |att|
    %tr
      %td= link_to "#{att.subject_type}", "#{project_path(@project)}/#{att.subject_type.downcase.pluralize}/#{att.subject_id}"
      %td= att.name
      %td= att.content_type
      %td= (att.content_size+512) >> 10
      %td= att.presenter.name if att.presenter
      %td= att.created_at.datetime_ydyn
      %td= att.tag
      %td= att.memo
      %td(style="text-align:right;")
        = link_to_function '查看', "view_image(#{att.id},'#{image_project_attachment_path(@project,att)}',#{att.image_width},600)" if att.image?
        = link_to '下载', download_project_attachment_path(@project,att)
= will_paginate @attachments

%br