config/routes.rb
# -*- encoding : utf-8 -*-

Rpmp::Application.routes.draw do

  namespace :sys do
    root :to => 'admin#facet', as: 'admin_root'
    resources :users do
      collection do
        get 'all', 'disabled'
      end
    end
    resources :departments, :roles, :mods do
      post 'tune_order', :on => :collection
    end
    resources :configs
    resources :dumps, :only => [:index,:create,:destroy] do
      post 'download', :on => :member
    end
    resources :projects do
      get *%w(all inactive), :on => :collection
      resources :role_members, :member_roles do
        get 'edit', :action => 'edit_all', :on => :collection
      end
    end
    resources :announcements do
      post 'issue', :on => :member
    end
    resource :logs, :only => :show
    controller :console, path: 'console', as: 'console' do
      get '/' => :index
      post 'run'
    end
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end

  controller :personal, path: 'personal', module: 'sys', as: 'personal' do
    get '/' => :index
    get 'edit'
    put 'update'
  end

  resources :projects do
    member do
      get *%w(role_members member_roles members)
    end
    collection do
      get *%w(all inactive activities weeklies issues_statistic
            issues issues_unsolved issues_to_test issues_closed issues_unclosed
            tasks tasks_todo my_tasks my_tasks_todo task_ranks task_matrix)
    end
    resources :attachments do
      member do
        get 'download', 'image'
      end
    end
    resources :modus do
      member do
        get *%w(requirements issues tasks)
      end
    end
    resources :tags, :only => [:index, :show] do
      member do
        get *%w(documents requirements issues tasks)
      end
    end
    resources :comments, :activities, :releases
    resources :documents, :meetings, :customers, :communications, :weeklies do
      get 'history', :on => :member
    end
    resources :requirements do
      get 'uncompleted', :on => :collection
      get 'history', :on => :member
    end
    resources :goals, :milestones, :controller => 'goals' do
      member do
        get 'release', 'history'
      end
    end
    resources :tests do
      get 'history', :on => :member
      resources :issues, :controller => :test_issues do
        collection do
          get 'unsolved', 'to_test'
        end
        get 'history', :on => :member
      end
    end
    resources :issues do
      collection do
        get *%w(unsolved to_test closed unclosed associated statistic)
      end
      member do
        get *%w(associated history solve regress reopen)
      end
    end
    resources :tasks, :my_tasks do
      collection do
        get *%w(todo requirements issues)
      end
      member do
        get *%w(history requirements issues)
        post *%w(receive rank)
      end
    end
    resource :task_statistics, only: 'show' do
      get 'ranks','matrix'
    end

    resources :revisions do
      get 'entries', :on => :member
      collection do
        get 'statistic'
        get 'diff/:entry_id(/:diff_with)', action: 'diff'
        get 'source/:entry_id', :action => 'source'
      end
    end
    post ':controller/:id/pm_confirm', :action => :pm_confirm
  end

  resources :announcements, :only => [:index, :show] do
    get 'current', :on => :collection
  end
  resources :departments, :only => [:index] do
    get 'users', :on => :member
  end
  resources :messages, :except => :update do
    collection do
      get 'received', 'sent'
    end
    get 'reply', :on => :member
  end

  match 'announcement' => 'announcements#current', :as => 'current_announcement'
  root :to => 'projects#index'

end

app/models/tag.rb
# -*- encoding : utf-8 -*-

class Tag < ActiveRecord::Base
  include ModelSupport

  belongs_to_project
  belongs_to_user :user
  belongs_to :subject, :polymorphic => true, :counter_cache => true

  def self.statistic(params)
    project_id=params[:project_id]
    project_id=project_id.to_i if project_id

    Task.connection.select_all <<-SQL
      select
        name,
        count(*) TOTAL,
        sum(if(subject_type='Document',1,0)) documents_count,
        sum(if(subject_type='Requirement',1,0)) requirements_count,
        sum(if(subject_type='Issue',1,0)) issues_count,
        sum(if(subject_type='Task',1,0)) tasks_count
      from tags
      #{" where project_id = #{project_id}" if project_id}
      group by name
      order by TOTAL desc
    SQL
  end

end

app/controllers/tags_controller.rb
# -*- encoding : utf-8 -*-

class TagsController < ProjectResourceController
  actions :ranks
  before_filter :set_tag_name, :except => [:index]

  def index
    @tag_statistic=Tag.statistic :project_id => @project.id
  end

  def show
    find_tags
  end

  def documents
    find_tags :subject_type => 'Document'
    render 'show'
  end

  def requirements
    find_tags :subject_type => 'Requirement'
    render 'show'
  end

  def issues
    find_tags :subject_type => 'Issue'
    render 'show'
  end

  def tasks
    find_tags :subject_type => 'Task'
    render 'show'
  end

  private

  def find_tags(condition={})
    condition[:name]=@name if @name && condition[:name].nil?
    @tags=Tag.where(condition).paginate(:page => params[:page])
  end

  def set_tag_name
    @name=params[:id]
  end

end

app/views/tags/_tags.html.haml
#tags_box{:style=>"display:#{resource.tags.any? ? 'block':'none'}"}
  %span.title 标签 &nbsp;&nbsp;
  - unless resource.respond_to?(:tags_count) and (resource.tags_count.nil? or resource.tags_count.zero?)
    - resource.tags.each do |tag|
      = tag.name
      &nbsp;&nbsp;

app/views/tags/index.html.haml
%h3 标签

%table.list-table
  %tr
    %th 标签
    %th 总数
    %th 文档
    %th 需求
    %th 问题
    %th 任务

  - @tag_statistic.each do |tag|
    %tr
      %td= tag['name']
      %td
        - unless nil_zero?(tag['TOTAL'])
          = link_to tag['TOTAL'].to_i, project_tag_path(@project,tag['name']), remote_options
      %td
        - unless nil_zero?(tag['documents_count'])
          = link_to tag['documents_count'].to_i, documents_project_tag_path(@project,tag['name']), remote_options
      %td
        - unless nil_zero?(tag['requirements_count'])
          = link_to tag['requirements_count'].to_i, requirements_project_tag_path(@project,tag['name']), remote_options
      %td
        - unless nil_zero?(tag['issues_count'])
          = link_to tag['issues_count'].to_i, issues_project_tag_path(@project,tag['name']), remote_options
      %td
        - unless nil_zero?(tag['tasks_count'])
          = link_to tag['tasks_count'].to_i, tasks_project_tag_path(@project,tag['name']), remote_options

%br

app/views/tags/show.html.haml
%h3
  标签
  - if @name
    %span(style="font-size:12px;")= "（#{@name}）"

%ul
  - @tags.each do |tag|
    %li
      = "#{tag.subject_type}："
      - subject=tag.subject
      - subject_name= subject.respond_to?(:abstract)? subject.abstract : subject.name
      = link_to "#{subject_name}", "#{project_path(@project)}/#{tag.subject_type.downcase.pluralize}/#{tag.subject_id}"

= will_paginate @tags

%br
  = link_to '返回', collection_path, remote_options